osx_image: xcode8.3

dist: trusty
sudo: false

language: c

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  yarn: true
  bundler: true
  directories:
    - node_modules
    - $HOME/.electron
    - $HOME/.cache
    - vendor/bundle

addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
  - case $TRAVIS_BRANCH in
      "production")
        echo -n echohub-packages-production > bucket;
        echo -n packages.echohub.io > domain;
        ;;
      *)
        echo -n echohub-packages-staging > bucket;
        echo -n packages.staging.echohub.io > domain;
        ;;
    esac;
  - sed -i.bak "s/ECHOHUB_BUCKET/$(cat bucket)/" package.json
  - sed -i.bak "s/ECHOHUB_DOMAIN/$(cat domain)/" package.json

install:
  - yarn install
  - bundle --deployment

script:
  - yarn run dist

after_script:
  - echo $GPG_PASSPHRASE | deb-s3 upload --bucket=$(cat bucket) --prefix=debian --codename=ubuntu --sign=$DEBSIGN_ID --gpg-options='--passphrase-fd 0' dist/*deb
