osx_image: xcode7.3

dist: trusty
sudo: false

language: c

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.cache

addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm
      # - libgnome-keyring-dev
      # - libsecret-1-dev

install:
  - yarn install
# - nvm install 7
# - yarn add electron-builder@next --dev # force install next version to test electron-builder

script:
  - yarn run build
  - yarn run dist

cache:
  yarn: true
  # directories:
  #   - node_modules
  # - ~/.electron
  #   - ~/.cache


# branches:
#   except:
#     - "/^v\\d+\\.\\d+\\.\\d+$/"
