osx_image: xcode7.3
dist: trusty

sudo: false
language: c

matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang

cache:
  yarn: true
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"

addons:
  apt:
    packages:
    - icnsutils
    - graphicsmagick
    - xz-utils
    - rpm

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH

install:
- yarn install

script:
- yarn run build
- yarn run dist

env:
  # AWS Keys
  global:
  - secure: XXfn+vJya5RDmKkJ021Om2025BEaAC68+aHqqCX0kDjrrUMONPM3BgH+OUBgN+vWC+Oz2AWAGEC/bhWrsOj5YM7odGzHLVqeBvM3WSksCsnQBqzxTJsVxmR86Fw1tSQ8hXKr2MaKThzXDeeiXvOIuEPw9szVqVR43Hkf0g2E+6Wim6yIVgTLnVB8tYXFxoOT/JDRTe2+K6hYJ8BNlFP2nTU05e57btXNq5S1m5VMtFTGAjhoPuHLcPFjjYkWX9oP+EQpolM/IsgzaAei8pmfCjTwA4HDQR7CO07d/CUbqcgGdJcJx/k6JJtI+yQkSn72U/y1D0jPUGT+DyHGD12g7kpxcWQ2xrMdJqcrHENoLFh4ffBZj7mQjPAZgkD4HE7b/1RRheHCS9u5mQVMlQTCSn7WmjHXH/VMM+4gi+qqMIsv1QrdQwS8ZEDwO+MoEYWTtPhwlcpNd9IY1JrEUh0B6Tmnp/Jex9pQ8OpQS/TdaSFQltn0k9RPl8TgtReeM6ALQkeRS30owmDgCbLJY0iUFhqksfogS4SQyfpyZhryy3mNEee6HhOt1VgqMbfJOQoUKGPH1n+efY9MGtisjs55PztD7MWP+BJAAwWHuizpM3WNzvee6q25GEXgUpcz8l+cWmmJMiEaNzGQdJaFQ7qwuW3MtzgqVuB3UDsvzgkAaxc=
  - secure: rGFYxlgQ53cXHGciQbrR0bsCI85Hxdc75IhYZDqN/oiXy2wKYQoIU6WxNjzfuqliogV2o4Kb0Pg1cmrRAU79UKv//FjdgZh7e/jZcAOsqyAU69TwicSpUxbuWzIjG01TlLZflp+hUCT/aX0EC8WdE09+W7H225BgYPB2NZCi4BsmW5ie2hWUFKS3iFyeheQF7DymGdfBbfIU1h+0Yeb87bCtgi7yYVyQMkZ/7UP/zEBZq5MU0JekOXs22tpsWechUKiVik472bYReEdVL0hvCJG01FTQhnM56abtIGuA0sQEmOdXiUzbsmEXyRDHpUhdJZBJ+ReLrgZT/bmLbZrMR+21yTfXULkD48ARlVWQ25KckLXAjnIQmM71F3D1Svg4Oc8OjlSn5KeDNylJyHyU/8dmb+wBdZG5DsNcOnEIE887f+Qr4yjtQBbkoUXxQGL15RMiWPw+jhFykyIF3Bm3GMjmwXhKcC4NlKGR8yJJisxAsLBdtEIfwK9Ccbd3utQP2QChJnSjQlJyFvuph5wcJqxc6B7mOMdchDlL6b97cqHE0Awr+yIJ++uLq++PDJiaKAjpPwYVUOpPKHOifxI6h+/7nOGg/k4xJ8lOrlfqa+v1tU2Da7cTkEyHUj5H6gVFZYFTjoHTDuZBXJ7CRXfewMMA9OrtokIMUvg9oDwPVYc=
