os: osx
osx_image: xcode8.3

language: node_js
node_js:
- "lts/*"

cache:
  yarn: true
  bundler: true
  directories:
    - $HOME/.electron
    - $HOME/Library/Caches/Homebrew

before_install:
  - case $TRAVIS_BRANCH in
      "production")
        echo -n echohub-packages-production > bucket;
        echo -n packages.echohub.io > domain;
        ;;
      *)
        echo -n echohub-packages-staging > bucket;
        echo -n packages.staging.echohub.io > domain;
        ;;
    esac;
  - sed -i.bak "s/ECHOHUB_BUCKET/$(cat bucket)/" package.json
  - sed -i.bak "s/ECHOHUB_DOMAIN/$(cat domain)/" package.json
  - brew install rpm
  - killall gpg-agent
  - gpg-agent --homedir /Users/travis/.gnupg --daemon --allow-preset-passphrase
  - echo $GPG_PASSPHRASE | /usr/local/Cellar/gnupg/2.1.21/libexec/gpg-preset-passphrase --preset 8A636ABAC529E6336AF85CAF7F1ADEE5B12A9FB4
  - echo $GPG_SECRET_KEYS | base64 --decode | GPG_TTY=$(tty) gpg --import

# install:
#   - yarn install
#   - bundle --deployment

script:
  - yarn run dist

after_script:
  - deb-s3 upload --bucket=$(cat bucket) --prefix=debian --codename=ubuntu --sign=$DEBSIGN_ID dist/*deb
