osx_image: xcode7.3

dist: trusty
sudo: false

language: c

matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang

cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.cache

addons:
  apt:
    packages:
    - icnsutils
    - graphicsmagick
    - xz-utils
    - rpm

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH

install:
- yarn install

script:
- yarn run dist
