os: osx
osx_image: xcode8.3

language: node_js
node_js:
- "lts/*"

branches:
  except:
    - /^v[0-9]/

cache:
  yarn: true
  bundler: true
  directories:
    - $HOME/.electron
    - $HOME/Library/Caches/Homebrew
    - vendor/bundle

before_install:
  - case $TRAVIS_BRANCH in
      "production")
        echo -n echohub-packages-production > bucket;
        echo -n packages.echohub.io > domain;
        ;;
      *)
        echo -n echohub-packages-staging > bucket;
        echo -n packages.staging.echohub.io > domain;
        ;;
    esac;
  - sed -i.bak "s/ECHOHUB_BUCKET/$(cat bucket)/" package.json
  - sed -i.bak "s/ECHOHUB_DOMAIN/$(cat domain)/" package.json
  - brew install rpm
  - echo $GPG_SECRET_KEYS | base64 --decode | GPG_TTY=$(tty) gpg --import --batch
  - bundle --deployment

script:
  - yarn run dist

after_script:
  - echo $GPG_PASSPHRASE | GPG_TTY=$(tty) bundle exec deb-s3 upload --bucket=$(cat bucket) --prefix=debian --codename=stable --sign=$DEBSIGN_ID --gpg-options='--passphrase-fd 0' dist/*deb
