osx_image: xcode8.3

language: node_js
node_js:
- "lts/*"

cache:
  yarn: true
  bundler: true
  directories:
    - $HOME/.electron
      # - $HOME/.cache
      # - vendor/bundle

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
  - case $TRAVIS_BRANCH in
      "production")
        echo -n echohub-packages-production > bucket;
        echo -n packages.echohub.io > domain;
        ;;
      *)
        echo -n echohub-packages-staging > bucket;
        echo -n packages.staging.echohub.io > domain;
        ;;
    esac;
  - sed -i.bak "s/ECHOHUB_BUCKET/$(cat bucket)/" package.json
  - sed -i.bak "s/ECHOHUB_DOMAIN/$(cat domain)/" package.json
  - brew install rpm

# install:
#   - yarn install
#   - bundle --deployment

script:
  - yarn run dist

after_script:
  - echo $GPG_PASSPHRASE | deb-s3 upload --bucket=$(cat bucket) --prefix=debian --codename=ubuntu --sign=$DEBSIGN_ID --gpg-options='--passphrase-fd 0' dist/*deb
